usr/bin/*
usr/lib/libqlcplusui*
usr/lib/libqlcplusengine*
usr/lib/libqlcpluswebaccess*
usr/share/qlcplus/documents/*
usr/share/applications/*
usr/share/pixmaps/*
usr/share/qlcplus/fixtures/*
usr/share/qlcplus/inputprofiles/*
usr/share/qlcplus/miditemplates/*
usr/share/qlcplus/modifierstemplates/*
usr/share/qlcplus/translations/*
usr/share/qlcplus/gobos/*
usr/share/qlcplus/rgbscripts/*
usr/share/qlcplus/web/*
usr/share/qlcplus/Sample.qxw
usr/share/mime/packages/qlcplus.xml

# Plugins
usr/lib/qt4/plugins/qlcplus/libenttecwing.so
usr/lib/qt4/plugins/qlcplus/libhidplugin.so
usr/lib/qt4/plugins/qlcplus/libdmx4linux.so
usr/lib/qt4/plugins/qlcplus/libmidiplugin.so
usr/lib/qt4/plugins/qlcplus/libdmxusb.so
usr/lib/qt4/plugins/qlcplus/libpeperoni.so
usr/lib/qt4/plugins/qlcplus/libudmx.so
usr/lib/qt4/plugins/qlcplus/libosc.so
usr/lib/qt4/plugins/qlcplus/libartnet.so
usr/lib/qt4/plugins/qlcplus/libe131.so
usr/lib/qt4/plugins/qlcplus/libspi.so
usr/lib/qt4/plugins/qlcplus/libloopback.so

# UDev rules
etc/udev/rules.d/z65-dmxusb.rules
etc/udev/rules.d/z65-peperoni.rules
etc/udev/rules.d/z65-anyma-udmx.rules
etc/udev/rules.d/z65-spi.rules
etc/udev/rules.d/z65-fx5-hid.rules
