usr/share/qlcplus/Sample.qxw
usr/share/qlcplus/fixtures/
usr/share/qlcplus/gobos/
usr/share/qlcplus/inputprofiles/
usr/share/qlcplus/miditemplates/
usr/share/qlcplus/modifierstemplates/
usr/share/qlcplus/rgbscripts/

usr/share/qlcplus/web/common.css
usr/share/qlcplus/web/configuration.js
usr/share/qlcplus/web/favicon-192x192.png
usr/share/qlcplus/web/favicon.ico
usr/share/qlcplus/web/keypad.html
usr/share/qlcplus/web/networkconfig.js
usr/share/qlcplus/web/websocket.js

usr/share/mime/packages/qlcplus.xml
usr/share/pixmaps/qlcplus.png

usr/share/metainfo/org.qlcplus.QLCPlus.dmx4linux.metainfo.xml
usr/share/metainfo/org.qlcplus.QLCPlus.dmxusb.metainfo.xml
usr/share/metainfo/org.qlcplus.QLCPlus.e131.metainfo.xml
usr/share/metainfo/org.qlcplus.QLCPlus.enttecwing.metainfo.xml
usr/share/metainfo/org.qlcplus.QLCPlus.hid.metainfo.xml
usr/share/metainfo/org.qlcplus.QLCPlus.loopback.metainfo.xml
usr/share/metainfo/org.qlcplus.QLCPlus.os2l.metainfo.xml
usr/share/metainfo/org.qlcplus.QLCPlus.osc.metainfo.xml
usr/share/metainfo/org.qlcplus.QLCPlus.peperoni.metainfo.xml
usr/share/metainfo/org.qlcplus.QLCPlus.spi.metainfo.xml
usr/share/metainfo/org.qlcplus.QLCPlus.udmx.metainfo.xml

# udev rules
etc/udev/rules.d/z65-dmxusb.rules
etc/udev/rules.d/z65-peperoni.rules
etc/udev/rules.d/z65-anyma-udmx.rules
etc/udev/rules.d/z65-spi.rules
etc/udev/rules.d/z65-fx5-hid.rules
